# Site settings
title: Keyboard Noises
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Edwin Tunggawan is a computer hobbyist, and by his laziness he ended up with sdsdkkk as his Twitter username. But it's used in his later accounts in other sites, as he's too lazy to think for another name.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sdsdkkk.github.io" # the base hostname & protocol for your site
twitter_username: sdsdkkk
github_username:  sdsdkkk

# Build settings
markdown: kramdown
