# Site settings
title: Some Title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm just trying out Jekyll, this site will be empty for a while
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sdsdkkk.github.io" # the base hostname & protocol for your site
twitter_username: sdsdkkk
github_username:  sdsdkkk

# Build settings
markdown: kramdown
